# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactorkit-example' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactorkit-example

  pod 'ReactorKit'
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxOptional'
  pod 'RxViewController'

end
